AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Name: "PPT PDF lambda"
Resources:
  pdfFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/ppt-pdf-lambda-1.0.0-shaded.jar
      Handler: com.business.unknown.APIHandler
      Runtime: java17
      Description: Java function
      MemorySize: 512
      Timeout: 10
      Events:
        PdfApi:
          Type: Api
          Properties:
            Path: /pdf
            Method: POST
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active